FORMAT: 1A
HOST: http://jsonplaceholder.typicode.com

# JSON Placeholder API
Fake Online REST API for Testing and Prototyping


# Group A Lovely Resource Group
All CRUD endpoints for A Lovely Resource Group



# Group An Awesome Resource Group
All non-CRUD endpoints



