FORMAT: 1A
HOST: http://jsonplaceholder.typicode.com

# JSON Placeholder API
Fake Online REST API for Testing and Prototyping


## /foos/{key}

+ Parameters
    + key: `ABeeSee` (string)

### Handle Get Foo [GET]
retrieves a single Foo

+ Response 200 

    + Body

            {
                "B": "A",
                "A": "Bee",
                "R": "See"
            }        


## /foos

### Handle Get Foos [GET]
retrieves the collection of Foos

+ Response 200 

    + Body

            {
                "2": {
                    "B": "",
                    "A": "",
                    "R": "2"
                },
                "ABeeSee": {
                    "B": "A",
                    "A": "Bee",
                    "R": "See"
                },
                "OneTwoThree": {
                    "B": "One",
                    "A": "Two",
                    "R": "Three"
                },
                "SomethingFunForYou": {
                    "B": "Something",
                    "A": "Fun",
                    "R": "ForYou"
                }
            }        


## /widgets/{id}

+ Parameters
    + id: `2` (number)

### Handle Get Widget [GET]
retrieves a single Widget

+ Response 200 

    + Body

            {
                "Id": 2,
                "Name": "Pencil",
                "Role": "Utensil"
            }        


## /widgets

### Handle Get Widgets [GET]
retrieves the collection of Wisdget

+ Response 200 

    + Body

            [
                {
                    "Id": 0,
                    "Name": "Nothing",
                    "Role": "N/A"
                },
                {
                    "Id": 1,
                    "Name": "Jibjab",
                    "Role": "Instrument"
                },
                {
                    "Id": 2,
                    "Name": "Pencil",
                    "Role": "Utensil"
                },
                {
                    "Id": 3,
                    "Name": "Fork",
                    "Role": "Utensil"
                },
                {
                    "Id": 4,
                    "Name": "Password",
                    "Role": "Credential"
                },
                {
                    "Id": 5,
                    "Name": "SpanFrankisco",
                    "Role": "Home"
                },
                {
                    "Id": 6,
                    "Name": "Doc",
                    "Role": "Villain"
                },
                {
                    "Id": 7,
                    "Name": "Coff3e",
                    "Role": "Hack"
                }
            ]        


### Handle Post Widget [POST]
adds a Widget to the collection

+ Request (application/json)

    + Body

            {
                "Id": 0,
                "Name": "anotherwidget",
                "Role": "controller"
            }        

+ Response 201 

    + Body

            {
                "Id": 8,
                "Name": "anotherwidget",
                "Role": "controller"
            }        


