
# Group Widgets

## /widgets/{id}

+ Parameters
    + id: `2` (number)

### Get Widget [GET]
retrieves a single Widget


+ Response 200 (application/json)



    + Body

            {
                "Id": 2,
                "Name": "Pencil",
                "Role": "Utensil"
            }        



+ Response 400 (text/plain; charset=utf-8)

    + Headers
            
            X-Content-Type-Options: nosniff

    + Body

            strconv.ParseInt: parsing "hello": invalid syntax
        



## /widgets

### Get Widgets [GET]
retrieves the collection of Wisdget


+ Response 200 (application/json)



    + Body

            [
                {
                    "Id": 0,
                    "Name": "Nothing",
                    "Role": "N/A"
                },
                {
                    "Id": 1,
                    "Name": "Jibjab",
                    "Role": "Instrument"
                },
                {
                    "Id": 2,
                    "Name": "Pencil",
                    "Role": "Utensil"
                },
                {
                    "Id": 3,
                    "Name": "Fork",
                    "Role": "Utensil"
                },
                {
                    "Id": 4,
                    "Name": "Password",
                    "Role": "Credential"
                },
                {
                    "Id": 5,
                    "Name": "SpanFrankisco",
                    "Role": "Home"
                },
                {
                    "Id": 6,
                    "Name": "Doc",
                    "Role": "Villain"
                },
                {
                    "Id": 7,
                    "Name": "Coff3e",
                    "Role": "Hack"
                }
            ]        


### Post Widget [POST]
adds a Widget to the collection


+ Request (application/json)



    + Body

            {
                "Id": 0,
                "Name": "anotherwidget",
                "Role": "controller"
            }        

+ Response 201 (application/json)



    + Body

            {
                "Id": 8,
                "Name": "anotherwidget",
                "Role": "controller"
            }        


